name: Build and Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: where am i?
      run: pwd && ls
    - name: run docker
      run: docker run ros:kinetic-perception ./build.sh
    - name: identify
      run: whoami