name: Build and Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: where am i?
      run: pwd && ls
    - name: run the build script inside of the ros docker image
      run: docker run -v /home/runner/work/chilitags/chilitags:/root ros:kinetic-perception /root/build.sh
    - name: identify
      run: whoami