name: Build and Deploy

on: [push]

jobs:
  build:

    runs-on: ubuntu-16.04
    
    steps:
    - uses: actions/checkout@v1
    - name: run docker
      run: docker run -it ros:kinetic-perception
    - name: identify
      run: whoami