name: Package

on:
  push:
    branches:    
    - '[A-Z]+-[0-9]+'
    - '[A-Z]+-[0-9]+/*'
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: package
        uses: ./.github/actions/package@local
      
         
