name: Development Package
on: pull_request
jobs:
  package:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: package
        id: package
        uses: ./.github/actions/package@local
        with:
          author: $GITHUB_ACTOR
          github-ref: $GITHUB_REF
      - name: The generated package
        run: echo "The artifact is ${{ steps.package.outputs.artifact-path }}"
         
