name: Story Development

on:
  push:
    branches-ignore:
      - master    
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: make
        uses: AutoModality/action-make-ros@BB-776/common-make


