name: Story

on:
  push:
    branches:    
    - '[A-Z]+-[0-9]+'
    - '[A-Z]+-[0-9]+/*'
jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v1
      - name: make
        uses: .github/actions/action-make-ros-kinetic-perception@3c43ed33982a7d473a937e50e51c8226651276e0
